apiVersion: v1
kind: Pod
metadata:
  name: application-probe
  labels:
    app: nginx
  namespace: application
spec:
  containers:
    - name: nginx
      image: nginx:latest 
      ports:
        - containerPort: 80
      readinessProbe:
        httpGet:
          path: /started
          port: 80
        initialDelaySeconds: 10
        periodSeconds: 5
        failureThreshold: 1
      livenessProbe:
        httpGet:
          path: /health
          port: 80
        initialDelaySeconds: 15
        periodSeconds: 10
        failureThreshold: 3
      