apiVersion: v1
kind: Pod
metadata:
  name: pi
  namespace: application
spec:
  containers:
  - name: pi
    image: perl:5.34.0
    command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(5000)"]
  restartPolicy: Never