apiVersion: v1
kind: Pod
metadata:
  name: akumo-pod
  namespace: application
spec:
  containers:
  - name: akumo-container
    image: busybox:1.35
    args: ["bin/sh", "-c", "sleep 5000"]
  restartPolicy: Never